version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    container_name: syncly-postgres
    environment:
      POSTGRES_DB: synclydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: noufalrahim
    ports:
      - "5432:5432"
    networks:
      - syncly-network
    volumes:
      - pgdata:/var/lib/postgresql/data  # persist DB data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syncly-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/synclydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: noufalrahim
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    depends_on:
      - postgres
    networks:
      - syncly-network
    volumes:
      - .:/app                    # mount source for hot reload
      - ~/.m2:/root/.m2           # cache Maven dependencies
    command: ./mvnw spring-boot:run -Dspring-boot.run.fork=false

networks:
  syncly-network:
    driver: bridge

volumes:
  pgdata:
